### ISSUE TITLE
Exception on first sample command

### ISSUE THREAD

**Issue by Remillard** [ThePlasmaRailgun/py-rolldice#2]
I was checking out the package to see if it would be suitable and tried the following in console from your documentation page:
```λ python
Python 3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 22:39:24) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import rolldice
>>> result, explanation = rolldice.roll_dice('12d6 + 10')
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\rolldice\rolldice.py", line 161, in _eval
    handler = self.nodes[type(node)]
KeyError: <class '_ast.Constant'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\rolldice\rolldice.py", line 855, in roll_dice
    final_result = parser.eval(''.join([str(x) for x in results])) #Call the parser to parse into one value
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\rolldice\rolldice.py", line 151, in eval
    return self._eval(ast.parse(expr.strip()).body[0].value)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\rolldice\rolldice.py", line 165, in _eval
    return handler(node)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\rolldice\rolldice.py", line 196, in _eval_binop
    return self.operators[type(node.op)](self._eval(node.left),
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\rolldice\rolldice.py", line 163, in _eval
    raise ValueError("Sorry, {0} is not available in this evaluator".format(type(node).__name__))
ValueError: Sorry, Constant is not available in this evaluator

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\rolldice\rolldice.py", line 859, in roll_dice
    raise DiceOperatorException('Error parsing operators and or functions')
rolldice.rolldice.DiceOperatorException: Error parsing operators and or functions
>>>
```

I haven't dug into it any further than that yet, though if I can figure out what's going on, I'll add to the issue.  Also note, version I was using was python 3.8.1.  The PyPI page said it was originally aimed at python 3.6, so that might be relevant.

**Comment by Remillard** [comment]
Well it fails similarly on a `1d6` string as well so it's pretty fundamental.  I do not understand the ast library enough to add more value here.  (Was originally just looking for a library to aid Blood Bowl 2 team and league management command line items in Discord.)  Best guess is that ast changed somehow.  I'll keep an eye on the issue as this was the best library candidate I found so far.

**Comment by Remillard** [comment]
I think I found the issue in general, though I do not know how to fix it:  From https://docs.python.org/3.8/library/ast.html 

> Deprecated since version 3.8: Class ast.Constant is now used for all constants. Old classes ast.Num, ast.Str, ast.Bytes, ast.NameConstant and ast.Ellipsis are still available, but they will be removed in future Python releases.

The traceback does seem to be getting fouled up on Constant, so this could be key.

**Comment by MajorTanya** [comment]
@Remillard 
I also experienced this issue on Python 3.8.2 and (seemingly) fixed it by changing line 131 in rolldice.py from `ast.Num: self._eval_num,` to `ast.Constant: self._eval_num,` (this was the only use of the `ast.Num` class that the Python 3.8 docs mentioned)

I tried out all of the example functions listed in the Readme.md and all of them worked as expected.

Now, I don't know if changing this line might impact some obscure methods the package uses, but for my purposes, it seems to be working perfectly fine.
I will open a pull request to fix this issue but I don't know if this will cause complications.

**Comment by NicklasTegner** [comment]
Hi. The current version from pypi is compatible with python 3.7 but still breaks on 3.8x with the traceback, that @Remillard showed in the original comment.
Any timeline for when #4 / #3 will be merged to fix the problem?

**Comment by MajorTanya** [comment]
0.4.0 should be working for Python 3.8 but not 3.7
0.3.9 is the one working for 3.7 and lower
Or did I misunderstand something?

**Comment by NicklasTegner** [comment]
no @MajorTanya it seems like I was in the wrong. For some reason my version was 0.3.9 not 0.4.0. Indeed 0.4.0 works with python 3.8x, while 0.3.9 does not (but does with 3.7x).

**Comment by ThePlasmaRailgun** [comment]
Oh, sorry, just merged it in.
